// <auto-generated />
using System;
using BlogPodrozniczy.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlogPodrozniczy.Web.Migrations
{
    [DbContext(typeof(BlogDB))]
    [Migration("20240121205853_1")]
    partial class _1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlogPodrozniczy.Web.Models.Domena.BlogPost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataPublikacji")
                        .HasColumnType("datetime2");

                    b.Property<string>("KrótkiOpis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nagłówek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Treść")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TytułStrony")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlZdjęcia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Widoczność")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Posty");
                });

            modelBuilder.Entity("BlogPodrozniczy.Web.Models.Domena.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WyświetlanaNazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tagi");
                });

            modelBuilder.Entity("BlogPostTag", b =>
                {
                    b.Property<Guid>("PostyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TagiId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PostyId", "TagiId");

                    b.HasIndex("TagiId");

                    b.ToTable("BlogPostTag");
                });

            modelBuilder.Entity("BlogPostTag", b =>
                {
                    b.HasOne("BlogPodrozniczy.Web.Models.Domena.BlogPost", null)
                        .WithMany()
                        .HasForeignKey("PostyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlogPodrozniczy.Web.Models.Domena.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
